prepare:
  name_files: 
    - WineQT.csv
    - WinePrices.csv
  x_columns:
    - fixed acidity
    - volatile acidity
    - citric acid
    - residual sugar
    - chlorides
    - free sulfur dioxide
    - total sulfur dioxide
    - density
    - pH
    - sulphates
    - alcohol
  target: price
  split: 0.33
train:
  model_name: RFR
  model_params:
    n_estimators: 500
    max_depth: 20
    min_samples_split: 2
    bootstrap: True
evaluate:
  model_name: RFR