prepare:
  name files: 
    - WineQT.csv
    - WinePrices.csv
  x columns:
    - fixed acidity
    - volatile acidity
    - citric acid
    - residual sugar
    - chlorides
    - free sulfur dioxide
    - total sulfur dioxide
    - density
    - pH
    - sulphates
    - alcohol
  target: price
  split: 0.33
train:
  model name: RFR
  model params:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    bootstrap: True